env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
  - id: go-musicfox-darwin-arm64
    main: ./main.go
    binary: test
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
  - id: go-musicfox-darwin-amd64
    main: ./main.go
    binary: test
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
