name: release

defaults:
  run:
    shell: bash

on: [push]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - run: git fetch --prune --unshallow

      - name: Setup go...
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"

      - name: release dry-run
        run: make release-dry-run
